-- The database under ./db is autogenerated. Changing the entries there
-- will result in a data loss whenever a new database gets extracted.
-- To be able to customize and/or fix entries that aren't yet detected
-- by the extractor logic, this file here can be used to save overwrites.

do -- area trigger

end

do -- items

end

do -- units/npcs
  -- Remove Silithus NPCs
  pfDB["units"]["data-epoch"][15174] = { } -- Calandrath
  pfDB["units"]["data-epoch"][15180] = { } -- Baristolth of the Shifting Sands
  pfDB["units"]["data-epoch"][15181] = { } -- Commander Mar'alith
  pfDB["units"]["data-epoch"][15183] = { } -- Geologist Larksbane
  pfDB["units"]["data-epoch"][15189] = { } -- Beetix Ficklespragg
  pfDB["units"]["data-epoch"][15270] = { } -- Huum Wildmane
  pfDB["units"]["data-epoch"][15282] = { } -- Aurel Goldleaf
  pfDB["units"]["data-epoch"][15306] = { } -- Bor Wildmane
  pfDB["units"]["data-epoch"][15498] = { } -- Windcaller Yessendra
  pfDB["units"]["data-epoch"][15499] = { } -- Frash Darksun
  pfDB["units"]["data-epoch"][15500] = { } -- Keyl Swiftclaw
  pfDB["units"]["data-epoch"][15540] = { } -- Windcaller Kaldon
  pfDB["units"]["data-epoch"][15599] = { } -- Elder Bronzebeard
  pfDB["units"]["data-epoch"][15797] = { } -- Colossus Researcher Sophia
  pfDB["units"]["data-epoch"][15798] = { } -- Master Sergeant Fizzlebolt
  pfDB["units"]["data-epoch"][15799] = { } -- Warlord Gorchuk
  pfDB["units"]["data-epoch"][16091] = { } -- Dirk Thunderwood
  pfDB["units"]["data-epoch"][17082] = { } -- Rifleman Torrig
  
  -- remove tbc npcs
  pfDB["units"]["data-epoch"][15563] = { } -- Elder Bellowrage
  pfDB["units"]["data-epoch"][16841] = { } -- Watch Commander Relthorn Netherwane
  pfDB["units"]["data-epoch"][17103] = { } -- Emissary Taluun
  pfDB["units"]["data-epoch"][19942] = { } -- Agent Proudwell <The Argent Dawn>
  pfDB["units"]["data-epoch"][10303] = { } -- Storm Shadowhoof
  pfDB["units"]["data-epoch"][13776] = { } -- Corporal Teeka Bloodsnarl
  pfDB["units"]["data-epoch"][13840] = { } -- Warmaster Laggrond
  pfDB["units"]["data-epoch"][14355] = { } -- Azj'Tordin
  pfDB["units"]["data-epoch"][14374] = { } -- Scholar Runethorn
  pfDB["units"]["data-epoch"][14846] = { } -- Lhara Darkmoon Faire NPC
  pfDB["units"]["data-epoch"][15021] = { } -- Deathmaster Dwire
  pfDB["units"]["data-epoch"][15126] = { } -- Rutherford Twing
  pfDB["units"]["data-epoch"][15192] = { } -- Anachronos
  pfDB["units"]["data-epoch"][16416] = { } -- Bronn Fitzwrench
  pfDB["units"]["data-epoch"][16417] = { } -- Rumsen Fizzlebrack
  pfDB["units"]["data-epoch"][17093] = { } -- Magistrix Elosai
  pfDB["units"]["data-epoch"][17094] = { } -- Nemeth Hawkeye
  pfDB["units"]["data-epoch"][17095] = { } -- Balandar Brightstar
  pfDB["units"]["data-epoch"][17097] = { } -- Advisor Sarophas
  pfDB["units"]["data-epoch"][17099] = { } -- Mehlar Dawnblade
  pfDB["units"]["data-epoch"][17106] = { } -- Vindicator Palanaar
  pfDB["units"]["data-epoch"][17127] = { } -- Anchorite Avuun
  pfDB["units"]["data-epoch"][17223] = { } -- Ambassador Rualeth
  pfDB["units"]["data-epoch"][17287] = { } -- Sentinel Luciel Starwhisper
  pfDB["units"]["data-epoch"][17303] = { } -- Vindicator Vedaar
  pfDB["units"]["data-epoch"][23535] = { } -- Matero Zeshuwal
  pfDB["units"]["data-epoch"][23566] = { } -- Calia Hastings
  pfDB["units"]["data-epoch"][23570] = { } -- Gizzix Grimegurgle
  pfDB["units"]["data-epoch"][23600] = { } -- Apprentice Morlann
  pfDB["units"]["data-epoch"][23601] = { } -- Apprentice Garion
  pfDB["units"]["data-epoch"][23723] = { } -- Sergeant Lukas
  pfDB["units"]["data-epoch"][23797] = { } -- Moxie Steelgrille
  pfDB["units"]["data-epoch"][23835] = { } -- Sergeant Amelyn
  pfDB["units"]["data-epoch"][23843] = { } -- Mordant Grimsby
  pfDB["units"]["data-epoch"][16287] = { } -- Ambassador Sunsorrow
  pfDB["units"]["data-epoch"][17355] = { } -- Valusha
  pfDB["units"]["data-epoch"][17109] = { } -- Cersei Dusksinger
  pfDB["units"]["data-epoch"][17098] = { } -- Ambassador Dawnsinger
  
  -- Remove zg island npc 
  pfDB["units"]["data-epoch"][14903] = { } -- Al'tabim the All-Seeing
  pfDB["units"]["data-epoch"][14910] = { } -- Exzhal
  pfDB["units"]["data-epoch"][14921] = { } -- Rin'wosho the Trader
  pfDB["units"]["data-epoch"][15070] = { } -- Vinchaxa

  -- Remove missing epl npcs will need to be added later with correct cords
  pfDB["units"]["data-epoch"][17069] = { } --Emissary Whitebeard 
  pfDB["units"]["data-epoch"][16112] = { } --Korfax, Champion of the Light 
  pfDB["units"]["data-epoch"][16116] = { } --Archmage Angela Dosantos 
  pfDB["units"]["data-epoch"][16131] = { } --Rohan the Assassin 
  pfDB["units"]["data-epoch"][16132] = { } --Huntsman Leopold 
  pfDB["units"]["data-epoch"][16133] = { } --Mataus the Wrathcaster 
  pfDB["units"]["data-epoch"][16135] = { } --Rayne 
  pfDB["units"]["data-epoch"][16212] = { } --Dispatch Commander Metz

  -- Removing DMF NPCs will return them at a later date once Epoch adds them. 
  pfDB["units"]["data-epoch"][14833] = { } -- Chronos
  pfDB["units"]["data-epoch"][14871] = { } -- Morja
  pfDB["units"]["data-epoch"][14841] = { } -- Rinling
  pfDB["units"]["data-epoch"][14828] = { } -- Gelvas Grimegate
  pfDB["units"]["data-epoch"][14832] = { } -- Kerri Hicks
  pfDB["units"]["data-epoch"][14829] = { } -- Yebb Neblegear
  pfDB["units"]["data-epoch"][14842] = { } -- Melnan Darkstone
  pfDB["units"]["data-epoch"][14843] = { } -- Kruban Darkblade

  -- Removing Linar Festival Units
  pfDB["units"]["data-epoch"][15556] = { } -- Elder Splitrock
  pfDB["units"]["data-epoch"][15557] = { } -- Elder Rumblerock
  pfDB["units"]["data-epoch"][15558] = { } -- Elder Silvervein
  pfDB["units"]["data-epoch"][15559] = { } -- Elder Highpeak
  pfDB["units"]["data-epoch"][15560] = { } -- Elder Stonefort
  pfDB["units"]["data-epoch"][15561] = { } -- Elder Obsidian
  pfDB["units"]["data-epoch"][15562] = { } -- Elder Hammershout
  pfDB["units"]["data-epoch"][15563] = { } -- Elder Bellowrage
  pfDB["units"]["data-epoch"][15564] = { } -- Elder Darkcore
  pfDB["units"]["data-epoch"][15565] = { } -- Elder Stormbrow
  pfDB["units"]["data-epoch"][15566] = { } -- Elder Snowcrown
  pfDB["units"]["data-epoch"][15567] = { } -- Elder Ironband
  pfDB["units"]["data-epoch"][15568] = { } -- Elder Graveborn
  pfDB["units"]["data-epoch"][15569] = { } -- Elder Goldwell
  pfDB["units"]["data-epoch"][15570] = { } -- Elder Primestone
  pfDB["units"]["data-epoch"][15572] = { } -- Elder Runetotem
  pfDB["units"]["data-epoch"][15573] = { } -- Elder Ragetotem
  pfDB["units"]["data-epoch"][15574] = { } -- Elder Stonespire
  pfDB["units"]["data-epoch"][15575] = { } -- Elder Bloodhoof
  pfDB["units"]["data-epoch"][15576] = { } -- Elder Winterhoof
  pfDB["units"]["data-epoch"][15577] = { } -- Elder Skychaser
  pfDB["units"]["data-epoch"][15578] = { } -- Elder Wildmane
  pfDB["units"]["data-epoch"][15579] = { } -- Elder Darkhorn
  pfDB["units"]["data-epoch"][15580] = { } -- Elder Proudhorn
  pfDB["units"]["data-epoch"][15581] = { } -- Elder Grimtotem
  pfDB["units"]["data-epoch"][15582] = { } -- Elder Windtotem
  pfDB["units"]["data-epoch"][15583] = { } -- Elder Thunderhorn
  pfDB["units"]["data-epoch"][15584] = { } -- Elder Skyseer
  pfDB["units"]["data-epoch"][15585] = { } -- Elder Dawnstrider
  pfDB["units"]["data-epoch"][15586] = { } -- Elder Dreamseer
  pfDB["units"]["data-epoch"][15587] = { } -- Elder Mistwalker
  pfDB["units"]["data-epoch"][15588] = { } -- Elder High Mountain
  pfDB["units"]["data-epoch"][15592] = { } -- Elder Windrun
  pfDB["units"]["data-epoch"][15593] = { } -- Elder Starsong
  pfDB["units"]["data-epoch"][15594] = { } -- Elder Moonstrike
  pfDB["units"]["data-epoch"][15595] = { } -- Elder Bladeleaf
  pfDB["units"]["data-epoch"][15596] = { } -- Elder Starglade
  pfDB["units"]["data-epoch"][15597] = { } -- Elder Moonwarden
  pfDB["units"]["data-epoch"][15598] = { } -- Elder Bladeswift
  pfDB["units"]["data-epoch"][15599] = { } -- Elder Bladesing
  pfDB["units"]["data-epoch"][15600] = { } -- Elder Skygleam
  pfDB["units"]["data-epoch"][15601] = { } -- Elder Starweave
  pfDB["units"]["data-epoch"][15602] = { } -- Elder Meadowrun
  pfDB["units"]["data-epoch"][15603] = { } -- Elder Nightwind
  pfDB["units"]["data-epoch"][15604] = { } -- Elder Morningdew
  pfDB["units"]["data-epoch"][15605] = { } -- Elder Riversong
  pfDB["units"]["data-epoch"][15606] = { } -- Elder Brightspear
  pfDB["units"]["data-epoch"][15607] = { } -- Elder Farwhisper
  pfDB["units"]["data-epoch"][15892] = { } -- Lunar Festival Emissary
  pfDB["units"]["data-epoch"][15871] = { } -- Elder Bronzebeard
  pfDB["units"]["data-epoch"][15864] = { } -- Valadar Starsong
  pfDB["units"]["data-epoch"][15909] = { } -- Fariel Starsong

  -- Remove Fire Festival
  pfDB["units"]["data-epoch"][25962] = { } -- Fire Eater
  pfDB["units"]["data-epoch"][25883] = { } -- Ashenvale Flame Warden
  pfDB["units"]["data-epoch"][25884] = { } -- Ashenvale Flame Keeper
  pfDB["units"]["data-epoch"][25887] = { } -- Arathi Flame Warden
  pfDB["units"]["data-epoch"][25888] = { } -- Azuremyst Isle Flame Warden
  pfDB["units"]["data-epoch"][25889] = { } -- Blade\'s Edge Flame Warden
  pfDB["units"]["data-epoch"][25890] = { } -- Blasted Lands Flame Warden
  pfDB["units"]["data-epoch"][25891] = { } -- Bloodmyst Isle Flame Warden
  pfDB["units"]["data-epoch"][25892] = { } -- Burning Steppes Flame Warden
  pfDB["units"]["data-epoch"][25893] = { } -- Darkshore Flame Warden
  pfDB["units"]["data-epoch"][25894] = { } -- Desolace Flame Warden
  pfDB["units"]["data-epoch"][25895] = { } -- Dun Morogh Flame Warden
  pfDB["units"]["data-epoch"][25896] = { } -- Duskwood Flame Warden
  pfDB["units"]["data-epoch"][25897] = { } -- Dustwallow Marsh Flame Warden
  pfDB["units"]["data-epoch"][25898] = { } -- Elwynn Forest Flame Warden
  pfDB["units"]["data-epoch"][25899] = { } -- Feralas Flame Warden
  pfDB["units"]["data-epoch"][25900] = { } -- Hellfire Peninsula Flame Warden
  pfDB["units"]["data-epoch"][25901] = { } -- Hillsbrad Flame Warden
  pfDB["units"]["data-epoch"][25902] = { } -- Loch Modan Flame Warden
  pfDB["units"]["data-epoch"][25903] = { } -- Nagrand Flame Warden
  pfDB["units"]["data-epoch"][25904] = { } -- Redridge Flame Warden
  pfDB["units"]["data-epoch"][25905] = { } -- Shadowmoon Valley Flame Warden
  pfDB["units"]["data-epoch"][25906] = { } -- Teldrassil Flame Warden
  pfDB["units"]["data-epoch"][25907] = { } -- Terokkar Forest Flame Warden
  pfDB["units"]["data-epoch"][25908] = { } -- The Hinterlands Flame Warden
  pfDB["units"]["data-epoch"][25909] = { } -- Western Plaguelands Flame Warden
  pfDB["units"]["data-epoch"][25910] = { } -- Westfall Flame Warden
  pfDB["units"]["data-epoch"][25911] = { } -- Wetlands Flame Warden
  pfDB["units"]["data-epoch"][25912] = { } -- Zangarmarsh Flame Warden
  pfDB["units"]["data-epoch"][25913] = { } -- Netherstorm Flame Warden
  pfDB["units"]["data-epoch"][25914] = { } -- Silithus Flame Warden
  pfDB["units"]["data-epoch"][25915] = { } -- Stranglethorn Vale Flame Warden
  pfDB["units"]["data-epoch"][25916] = { } -- Tanaris Flame Warden
  pfDB["units"]["data-epoch"][25917] = { } -- Winterspring Flame Warden
  pfDB["units"]["data-epoch"][25918] = { } -- Netherstorm Flame Keeper
  pfDB["units"]["data-epoch"][25919] = { } -- Silithus Flame Keeper
  pfDB["units"]["data-epoch"][25920] = { } -- Stranglethorn Vale Flame Keeper
  pfDB["units"]["data-epoch"][25921] = { } -- Tanaris Flame Keeper
  pfDB["units"]["data-epoch"][25922] = { } -- Winterspring Flame Keeper
  pfDB["units"]["data-epoch"][25923] = { } -- Arathi Flame Keeper
  pfDB["units"]["data-epoch"][25924] = { } -- Twilight Speaker Viktor
  pfDB["units"]["data-epoch"][25925] = { } -- Badlands Flame Keeper
  pfDB["units"]["data-epoch"][25926] = { } -- Blade\'s Edge Flame Keeper
  pfDB["units"]["data-epoch"][25927] = { } -- Burning Steppes Flame Keeper
  pfDB["units"]["data-epoch"][25928] = { } -- Desolace Flame Keeper
  pfDB["units"]["data-epoch"][25929] = { } -- Durotar Flame Keeper
  pfDB["units"]["data-epoch"][25930] = { } -- Dustwallow Marsh Flame Keeper
  pfDB["units"]["data-epoch"][25931] = { } -- Eversong Woods Flame Keeper
  pfDB["units"]["data-epoch"][25932] = { } -- Feralas Flame Keeper
  pfDB["units"]["data-epoch"][25933] = { } -- Ghostlands Flame Keeper
  pfDB["units"]["data-epoch"][25934] = { } -- Hellfire Peninsula Flame Keeper
  pfDB["units"]["data-epoch"][25935] = { } -- Hillsbrad Flame Keeper
  pfDB["units"]["data-epoch"][25936] = { } -- Mulgore Flame Keeper
  pfDB["units"]["data-epoch"][25937] = { } -- Nagrand Flame Keeper
  pfDB["units"]["data-epoch"][25938] = { } -- Shadowmoon Valley Flame Keeper
  pfDB["units"]["data-epoch"][25939] = { } -- Silverpine Forest Flame Keeper
  pfDB["units"]["data-epoch"][25940] = { } -- Stonetalon Flame Keeper
  pfDB["units"]["data-epoch"][25941] = { } -- Swamp of Sorrows Flame Keeper
  pfDB["units"]["data-epoch"][25942] = { } -- Terokkar Forest Flame Keeper
  pfDB["units"]["data-epoch"][25943] = { } -- The Barrens Flame Keeper
  pfDB["units"]["data-epoch"][25944] = { } -- The Hinterlands Flame Keeper
  pfDB["units"]["data-epoch"][25945] = { } -- Thousand Needles Flame Keeper
  pfDB["units"]["data-epoch"][25946] = { } -- Tirisfal Glades Flame Keeper
  pfDB["units"]["data-epoch"][25947] = { } -- Zangarmarsh Flame Keeper
  pfDB["units"]["data-epoch"][24519] = { } -- Costumed Orphan Matron
  pfDB["objects"]["data-epoch"][187559] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187917] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187919] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187920] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187921] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187922] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187923] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187925] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187926] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187927] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187928] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187929] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187930] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187933] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187935] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187937] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187939] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187941] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187942] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187947] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187948] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187949] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187950] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187951] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187952] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187953] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187955] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187958] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187960] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187962] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187963] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187964] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187965] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187966] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187967] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187970] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187972] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187973] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187974] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187975] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187914] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187916] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187924] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187931] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187932] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187934] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187936] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187938] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187940] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187943] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187944] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187945] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187946] = { } -- Alliance Bonfire
  pfDB["objects"]["data-epoch"][187954] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187956] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187957] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187959] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187961] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187968] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187969] = { } -- Horde Bonfire
  pfDB["objects"]["data-epoch"][187971] = { } -- Horde Bonfire
  pfDB["units"]["data-epoch"][16817] = { } -- Festival Loremaster
  pfDB["units"]["data-epoch"][25975] = { } -- Master Fire Eater
  pfDB["units"]["data-epoch"][26221] = { } -- Earthen Ring Elder
  pfDB["units"]["data-epoch"][19148] = { } -- Dwarf Commoner
  pfDB["units"]["data-epoch"][19172] = { } -- Dwarf Commoner
  

  -- Remove Holloween
  pfDB["objects"]["data-epoch"][189303] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190034] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190035] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190036] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190037] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190038] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190039] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190040] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190041] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190042] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190043] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190044] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190045] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190046] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190047] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190048] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190049] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190050] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190051] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190052] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190053] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190054] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190055] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190056] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190057] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190058] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190059] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190060] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190061] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190062] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190063] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190064] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190065] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190066] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190067] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190068] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190069] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190070] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190071] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190072] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190073] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190074] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190075] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190076] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190077] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190078] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190079] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190080] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190081] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190082] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190083] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190084] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190085] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190086] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190087] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190088] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190089] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190090] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190091] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190096] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190097] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190098] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190099] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190100] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190101] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190102] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190103] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190104] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190105] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190106] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190107] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190108] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190109] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190110] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190111] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190112] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190113] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190114] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190115] = { } -- Candy Bucket
  pfDB["objects"]["data-epoch"][190116] = { } -- Candy Bucket
  pfDB["units"]["data-epoch"][15310] = { } -- Jesper

  -- Remove Christmas and New Years
  pfDB["units"]["data-epoch"][15732] = { } -- Wonderform Operator
  pfDB["units"]["data-epoch"][13435] = { } -- Khole Jinglepocket
  pfDB["objects"]["data-epoch"][180743] = { } -- xmas Present
  pfDB["objects"]["data-epoch"][180793] = { } -- xmas Present
  pfDB["objects"]["data-epoch"][180748] = { } -- xmas Present
  pfDB["objects"]["data-epoch"][180746] = { } -- xmas Present
  pfDB["objects"]["data-epoch"][180747] = { } -- xmas Present
  pfDB["objects"]["data-epoch"][187236] = { } -- xmas Present
  pfDB["units"]["data-epoch"][1365] = { } -- Goli Krumn
  pfDB["units"]["data-epoch"][13433] = { } -- Wulmort Jinglepocket
  pfDB["units"]["data-epoch"][13444] = { } -- Greatfather Winter
  pfDB["units"]["data-epoch"][13418] = { } -- Kaymard Copperpinch

  -- Remove Scourge Event
  pfDB["units"]["data-epoch"][16484] = { } -- Lieutenant Nevell
  pfDB["units"]["data-epoch"][16478] = { } -- Lieutenant Orrin
  pfDB["units"]["data-epoch"][16494] = { } -- Lieutenant Rukag
  pfDB["units"]["data-epoch"][16361] = { } -- Commander Thomas Helleran
  pfDB["units"]["data-epoch"][16495] = { } -- Lieutenant Beitha
  pfDB["units"]["data-epoch"][16493] = { } -- Lieutenant Dagel
  pfDB["units"]["data-epoch"][16490] = { } -- Lieutenant Lisande

  -- Remove Wickerman
  pfDB["units"]["data-epoch"][15199] = { } -- Sergeant Hartman
  
  -- Remove Love is in the air
  pfDB["units"]["data-epoch"][16075] = { } -- Kwee Q. Paddlefeet
  pfDB["units"]["data-epoch"][16005] = { } -- Lieutenant Jocryn Heldric
  pfDB["units"]["data-epoch"][16105] = { } -- Aristan Mottar
  pfDB["units"]["data-epoch"][16009] = { } -- Tormek Stoneriver
  pfDB["units"]["data-epoch"][16001] = { } -- Aldris Fourclouds

  -- Remove Brewfest
  pfDB["units"]["data-epoch"][18927] = { } -- Human Commoner
  pfDB["objects"]["data-epoch"][186881] = { } -- Human Commoner

  -- Remove Harvest Festival
  pfDB["units"]["data-epoch"][15011] = { } -- Wagner Hammerstrike

  -- Remove AQ War Effort
  pfDB["units"]["data-epoch"][15766] = { } -- Officer Maloof
  pfDB["units"]["data-epoch"][15708] = { } -- Master Sergeant Maclure
  pfDB["units"]["data-epoch"][15762] = { } -- Officer Lunalight
  pfDB["units"]["data-epoch"][15709] = { } -- Master Sergeant Moonshadow
  pfDB["units"]["data-epoch"][15707] = { } -- Master Sergeant Fizzlebolt
  pfDB["units"]["data-epoch"][15764] = { } -- Officer Ironbeard
  pfDB["units"]["data-epoch"][15763] = { } -- Officer Porterhouse

  pfDB["units"]["data-epoch"][15701] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15453] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15452] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15451] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15701] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15446] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15448] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15733] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15450] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15734] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15731] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15735] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15432] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15383] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15431] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15437] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15457] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15455] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15437] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15445] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15434] = { } -- war effort npc ironforge
  pfDB["units"]["data-epoch"][15456] = { } -- war effort npc ironforge

end

do -- quests
  pfDB["quests"]["data-epoch"][9] = { } -- Quest Removed - The Killing Fields
  pfDB["quests"]["data-epoch"][498] = { } --The Rescue - Durnhold Keep
  pfDB["quests"]["data-epoch"][526] = { } --Remove unused Lightforge Ingots
  pfDB["quests"]["data-epoch"][549] = { } --WANTED: Syndicate Personnel
  pfDB["quests"]["data-epoch"][899] = { } --Consumed by Hatred
  pfDB["quests"]["data-epoch"][934] = { } -- OLD Crown Of The Earth
  pfDB["quests"]["data-epoch"][1070] = { } -- On Guard in Stonetalon 
  pfDB["quests"]["data-epoch"][4921] = { } --Lost in Battle
  pfDB["quests"]["data-epoch"][5527] = { } --A Reliquary of Purity
  pfDB["quests"]["data-epoch"][7863] = { } -- Sentinel Basic Care Package
  pfDB["quests"]["data-epoch"][7864] = { } -- Sentinel Standard Care Package
  pfDB["quests"]["data-epoch"][7865] = { } -- Sentinel Advanced Care Package
  pfDB["quests"]["data-epoch"][7866] = { } --Outrider Basic Care Package
  pfDB["quests"]["data-epoch"][7867] = { } --Outrider Standard Care Package
  pfDB["quests"]["data-epoch"][7868] = { } --Outrider Advanced Care Package
  pfDB["quests"]["data-epoch"][7874] = { } --Quell the Silverwing Usurpers
  pfDB["quests"]["data-epoch"][7875] = { } --Quell the Silverwing Usurpers
  pfDB["quests"]["data-epoch"][7876] = { } --Quell the Silverwing Usurpers
  pfDB["quests"]["data-epoch"][9435] = { } --Remove tbc quest Missing crystals
  pfDB["quests"]["data-epoch"][9516] = { } -- Destroy the Legion A
  pfDB["quests"]["data-epoch"][9518] = { } -- Agents of Destruction
  pfDB["quests"]["data-epoch"][9519] = { } -- The Lost Chalice
  pfDB["quests"]["data-epoch"][9521] = { } -- Report from the Northern Front
  pfDB["quests"]["data-epoch"][11211] = { } -- Help for Mudsprocket
  pfDB["quests"]["data-epoch"][11212] = { } -- Tabetha's Farm
  pfDB["quests"]["data-epoch"][11214] = { } -- Mission to Mudsprocket
  pfDB["quests"]["data-epoch"][11451] = { } --Remove tbc quest Alicia's Poem
  pfDB["quests"]["data-epoch"][182] = { } --Remove dwarf quest The Troll Cave
  pfDB["quests"]["data-epoch"][8551] = { } --Remove The Captain's Chest (Non elite version)
  pfDB["quests"]["data-epoch"][3361] = { } -- Remove Original Refugee's Quandary
  pfDB["quests"]["data-epoch"][551] = { } -- Remove Original The Ensorcelled Parchment
  pfDB["quests"]["data-epoch"][11185] = { } -- Remove The Apothecary's Letter
  pfDB["quests"]["data-epoch"][11186] = { } -- Remove Signs of Treachery?
end

do -- Objects
  -- Remove TBC wanted sign
  pfDB["objects"]["data-epoch"][186426] = { }

  -- Remove Silithus Wanted Poster: Deathclasp
  pfDB["objects"]["data-epoch"][180448] = { }
end