name: Release pfQuest-epoch on changes
on:
  workflow_dispatch:
permissions:
  contents: write
  actions: read
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Extract version from TOC file
        id: get_version
        run: |
          VERSION=$(grep "## Version:" pfQuest-epoch.toc | sed 's/## Version: //')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"
      
      - name: Create pfQuest-epoch zip
        run: |
          mkdir pfQuest-epoch
          rsync -av --exclude='.git' --exclude='.github' --exclude='*.md' --exclude='LICENSE' --exclude='.gitattributes' --exclude='pfQuest-epoch' . pfQuest-epoch/
          zip -r pfQuest-epoch.zip pfQuest-epoch/
      
      - name: Create Versioned Release and Upload Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: pfQuest-epoch-v${{ steps.get_version.outputs.version }}
          name: pfQuest-epoch v${{ steps.get_version.outputs.version }}
          files: pfQuest-epoch.zip
          make_latest: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}